# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y6f3xAW-9TmzRz59NjTENbN9M9-A-o4H
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/app.py

!pip install streamlit
import time
import random
import streamlit as st

class ZomatoCSAOPipeline:
    def __init__(self):
        # EXPANDED CATALOG to support 8-10 distinct recommendations
        self.food_graph = {
            # Mains
            'Chicken Biryani': {'type': 'Main', 'needs': ['Side', 'Beverage', 'Dessert']},
            'Margherita Pizza': {'type': 'Main', 'needs': ['Side', 'Beverage', 'Dessert']},
            # Sides
            'Mint Raita': {'type': 'Side'}, 'Garlic Bread': {'type': 'Side'},
            'Extra Cheese': {'type': 'Side'}, 'French Fries': {'type': 'Side'},
            'Masala Papad': {'type': 'Side'}, 'Spicy Salan': {'type': 'Side'},
            # Beverages
            'Coke': {'type': 'Beverage'}, 'Filter Coffee': {'type': 'Beverage'},
            'Fresh Lime Soda': {'type': 'Beverage'}, 'Cold Coffee': {'type': 'Beverage'},
            'Iced Tea': {'type': 'Beverage'},
            # Desserts
            'Gulab Jamun': {'type': 'Dessert'}, 'Chocolate Brownie': {'type': 'Dessert'},
            'Ice Cream': {'type': 'Dessert'}, 'Cheesecake': {'type': 'Dessert'},
            'Rasmalai': {'type': 'Dessert'}
        }

        # Cold start items now mapped to categories
        self.cold_start_inventory = {
            'Truffle Fries (NEW)': 'Side',
            'Mango Lassi (NEW)': 'Beverage',
            'Biscoff Cheesecake (NEW)': 'Dessert'
        }
        self.all_addons = [k for k, v in self.food_graph.items() if v['type'] != 'Main']

    def _get_redis_user_features(self, user_id):
        mock_redis_store = {
            'U1001': {'diet_trend': 'Junk', 'frequent_items': ['Filter Coffee', 'Coke', 'French Fries']},
            'U1002': {'diet_trend': 'Healthy', 'frequent_items': ['Mint Raita', 'Fresh Lime Soda']}
        }
        return mock_redis_store.get(user_id, {'diet_trend': 'Balanced', 'frequent_items': []})

    def _generate_ui_badge(self, item, user_features, graph_boost):
        if item in user_features['frequent_items']: return " Your Usual"
        elif graph_boost > 0: return " Perfect Match"
        elif item in self.cold_start_inventory: return "New on Menu"
        else: return " Popular Choice"

    def predict_addons(self, user_id, current_cart, top_n=9):
        start_time = time.time()
        user_features = self._get_redis_user_features(user_id)

        # 1. Identify missing slots based on the cart
        missing_slots = set()
        for cart_item in current_cart:
            if cart_item in self.food_graph:
                missing_slots.update(self.food_graph[cart_item].get('needs', []))

        # Fallback if cart is empty or unrecognized
        if not missing_slots: missing_slots = {'Side', 'Beverage', 'Dessert'}

        # 2. Score candidates and group them by category
        categorized_candidates = {slot: [] for slot in missing_slots}
        for item in self.all_addons:
            if item in current_cart: continue

            item_type = self.food_graph[item]['type']
            if item_type not in missing_slots: continue

            base_score = random.uniform(0.4, 0.7)
            graph_boost = 0.25 # Boost for filling a missing slot
            final_score = base_score + graph_boost

            categorized_candidates[item_type].append({
                'item': item,
                'score': round(final_score, 3),
                'ui_badge': self._generate_ui_badge(item, user_features, graph_boost),
                'category': item_type
            })

        # 3. QUOTA ALLOCATION: Distribute the 9 items evenly
        num_slots = len(missing_slots)
        base_quota = top_n // num_slots
        remainder = top_n % num_slots

        final_recommendations = []
        for i, slot in enumerate(missing_slots):
            quota = base_quota + (1 if i < remainder else 0)
            # Sort items in this category by score and take the top `quota` amount
            sorted_items = sorted(categorized_candidates[slot], key=lambda x: x['score'], reverse=True)
            final_recommendations.extend(sorted_items[:quota])

        # 4. BANDIT LOGIC: Inject a new item into its corresponding category 15% of the time
        if random.random() < 0.15:
            bandit_slot = random.choice(list(missing_slots))
            valid_bandits = [k for k, v in self.cold_start_inventory.items() if v == bandit_slot]
            if valid_bandits:
                bandit_item = random.choice(valid_bandits)
                bandit_entry = {
                    'item': bandit_item, 'score': 0.99, 'category': bandit_slot,
                    'ui_badge': self._generate_ui_badge(bandit_item, user_features, 0)
                }
                # Replace the lowest scoring item in that category to maintain the quota
                cat_indices = [idx for idx, x in enumerate(final_recommendations) if x['category'] == bandit_slot]
                if cat_indices:
                    idx_to_replace = cat_indices[-1] # Last item is the lowest score due to prior sorting
                    final_recommendations[idx_to_replace] = bandit_entry

        latency_ms = round((time.time() - start_time) * 1000, 2)
        return final_recommendations, latency_ms

st.set_page_config(page_title="Zomathon CSAO Engine", layout="wide")

@st.cache_resource
def load_pipeline():
    return ZomatoCSAOPipeline()

pipeline = load_pipeline()

if 'cart' not in st.session_state: st.session_state.cart = []

st.markdown("<h1 style='text-align: center; color: #E23744;'>Zomato CSAO Engine: Diverse Meal Completion</h1>", unsafe_allow_html=True)
st.divider()

#  SIDEBAR
with st.sidebar:
    st.header(" Simulated User")
    user_id = st.selectbox("Select User Profile", ["U1001 (Frequent Coke/Fries)", "U1002 (Healthy Eater)"])
    user_id_clean = user_id.split(" ")[0]

    st.header("Your Cart")
    if not st.session_state.cart:
        st.info("Your cart is empty.")
    else:
        for item in st.session_state.cart: st.markdown(f"- **{item}**")
        if st.button(" Clear Cart"):
            st.session_state.cart = []
            st.rerun()

# MAIN DASHBOARD
st.subheader("Step 1: Add a Main Dish")
col_m1, col_m2 = st.columns(2)
with col_m1:
    if st.button(" Add Chicken Biryani"):
        st.session_state.cart.append("Chicken Biryani")
        st.rerun()
with col_m2:
    if st.button(" Add Margherita Pizza"):
        st.session_state.cart.append("Margherita Pizza")
        st.rerun()

st.divider()

if st.session_state.cart:
    st.subheader(" Step 2: Complete Your Meal (Top 9 Add-ons)")

    # Run the prediction pipeline requesting 9 items
    recommendations, latency = pipeline.predict_addons(user_id_clean, st.session_state.cart, top_n=9)
    st.success(f" Inference Latency: **{latency} ms** (SLA: < 300ms)")

    # Group recommendations by category for UI display
    grouped_recs = {'Side': [], 'Beverage': [], 'Dessert': []}
    for rec in recommendations:
        grouped_recs[rec['category']].append(rec)

    # Display in 3 Columns
    col1, col2, col3 = st.columns(3)

    columns_map = {
        'Side': (col1, " Sides & Accompaniments"),
        'Beverage': (col2, " Refreshing Beverages"),
        'Dessert': (col3, " Sweet Desserts")
    }

    for category, (col_obj, title) in columns_map.items():
        with col_obj:
            st.markdown(f"### {title}")
            if not grouped_recs[category]:
                st.write("No recommendations needed.")
            for rec in grouped_recs[category]:
                with st.container():
                    st.markdown(f"""
                    <div style="border: 1px solid #ddd; border-radius: 8px; padding: 12px; margin-bottom: 10px; background-color: #fcfcfc;">
                        <h5 style="margin: 0; color: #333;">{rec['item']}</h5>
                        <div style="margin-top: 5px; margin-bottom: 8px;">
                            <span style="background-color: #ffcccc; color: #b30000; padding: 3px 6px; border-radius: 4px; font-size: 0.75em; font-weight: bold;">{rec['ui_badge']}</span>
                        </div>
                        <p style="margin: 0; font-size: 0.8em; color: #777;">Score: {rec['score']}</p>
                    </div>
                    """, unsafe_allow_html=True)
else:
    st.info(" Add a Main Dish to trigger the Cart Super Add-On recommendations!")